config/routes.rb
Rails.application.routes.draw do
  root 'root#index'

  get 'game/new', to: 'game#new', as: :new_game
  get 'game/find', to: 'game#find', as: :find_game
  get 'game/:id', to: 'game#show', as: :game


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game
  @@rooms = {}

  attr :id, :players, :status, :number, :current_player_index, :current_player_id

  def initialize
    @id = SecureRandom.urlsafe_base64(12)
    @players = []
    @status = 'new'
    @@rooms[@id] = self
  end

  def self.find(id)
    @@rooms[id]
  end

  def join(player)
    if @status != 'playing'
      if @players.select { |e| e['id'] == player['id'] }.blank?
        @players.push player
        @status = 'joined'
      end
    end
  end

  def ready(player_id)
    if @status != 'playing'
      @status = 'ready'
      @players.map { |e| e['ready'] = true if e['id'] == player_id }
      start if @players.map { |e| e['ready'] }.reduce(:&)
    end
  end

  def start
    if @status == 'ready'
      @status = 'playing'
      @players.shuffle
      @current_player_index = 0
      @current_player_id = @players[@current_player_index]['id']
    end
  end

  def move(player_id, number)
    if @status == 'playing'
      @number = number
      @current_player_index = (@current_player_index+1) % @players.size 
      @current_player_id = @players[@current_player_index]['id']
    end
  end

  def update_player(updated_player)
    if @status == 'playing'
      @players.map { |e| e.merge!(updated_player) if e['id'] == updated_player['id'] }
    end
  end

  def end
    if @status == 'playing'
      @status = 'ended'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def show
    game = Game.find(params[:id])
    return redirect_to root_path unless game
    return redirect_to root_path if game.status == 'ended'
  end
  
  def new
    game = Game.new()
    redirect_to game_path(id: game.id)
  end

  def find
    redirect_to game_path(id: params[:id])
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/game/show.html.erb
<div class="row">
  <div class="game-board">
    <div class="row">
      <div id="cell_00" class="cell pristine" data-position='{"row": 0, "col": 0}'></div>
      <div id="cell_01" class="cell pristine" data-position='{"row": 0, "col": 1}'></div>
      <div id="cell_02" class="cell pristine" data-position='{"row": 0, "col": 2}'></div>
      <div id="cell_03" class="cell pristine" data-position='{"row": 0, "col": 3}'></div>
      <div id="cell_04" class="cell pristine" data-position='{"row": 0, "col": 4}'></div>
    </div>
    <div class="row">
      <div id="cell_10" class="cell pristine" data-position='{"row": 1, "col": 0}'></div>
      <div id="cell_11" class="cell pristine" data-position='{"row": 1, "col": 1}'></div>
      <div id="cell_12" class="cell pristine" data-position='{"row": 1, "col": 2}'></div>
      <div id="cell_13" class="cell pristine" data-position='{"row": 1, "col": 3}'></div>
      <div id="cell_14" class="cell pristine" data-position='{"row": 1, "col": 4}'></div>
    </div>
    <div class="row">
      <div id="cell_20" class="cell pristine" data-position='{"row": 2, "col": 0}'></div>
      <div id="cell_21" class="cell pristine" data-position='{"row": 2, "col": 1}'></div>
      <div id="cell_22" class="cell pristine" data-position='{"row": 2, "col": 2}'></div>
      <div id="cell_23" class="cell pristine" data-position='{"row": 2, "col": 3}'></div>
      <div id="cell_24" class="cell pristine" data-position='{"row": 2, "col": 4}'></div>
    </div>
    <div class="row">
      <div id="cell_30" class="cell pristine" data-position='{"row": 3, "col": 0}'></div>
      <div id="cell_31" class="cell pristine" data-position='{"row": 3, "col": 1}'></div>
      <div id="cell_32" class="cell pristine" data-position='{"row": 3, "col": 2}'></div>
      <div id="cell_33" class="cell pristine" data-position='{"row": 3, "col": 3}'></div>
      <div id="cell_34" class="cell pristine" data-position='{"row": 3, "col": 4}'></div>
    </div>
    <div class="row">
      <div id="cell_40" class="cell pristine" data-position='{"row": 4, "col": 0}'></div>
      <div id="cell_41" class="cell pristine" data-position='{"row": 4, "col": 1}'></div>
      <div id="cell_42" class="cell pristine" data-position='{"row": 4, "col": 2}'></div>
      <div id="cell_43" class="cell pristine" data-position='{"row": 4, "col": 3}'></div>
      <div id="cell_44" class="cell pristine" data-position='{"row": 4, "col": 4}'></div>
    </div>
  </div>
</div>

<div class="row your-turn" style="display: none">
  <p>Your turn</p>
</div>
<div class="row actions">
  <p>
    <a href="javascript:null" class="btn" id="randomBtn">Random</a>
    <a href="javascript:null" class="btn" id="readyBtn">Ready</a>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bingo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/root/index.html.erb
<div class="root-content">
  <h1 class="title">Hi, <span class="inline-input" id="playerName" contenteditable="true">You</span>!</h1>
  <div class="row">
    <%= link_to 'Play', new_game_path, class: 'btn' %>
  </div>
</div>